QPID-8454 Add prometheus metrics
apache/qpid-broker-j pull request #56
Opened 2020-08-28 14:09 UTC by Dedeepya-T

The Pull Request adds the Qpid Broker integration with Prometheus
* a new broker plugin modules qpid-prometheus-exporter is added to collect Qpid broker statistics as Prometheus metrics
* QpidCollector implements the Prometheus Client Collector interface
* a new Plugin interface ContentFactory is added into the broker-core
* an implementation of ContentFactory is for Prometheus metrics
* a new servlet is added to serve content generated with ContentFactory
* Prometheus servlets are mapped under /metrics and /metrics/*
* /metrics serves broker metrics
* /metrics/<virtual host node name>/<virtual host name> serves Virtual host metrics

2020-08-30 22:17 UTC, alex-rufous requested changes
Hi Dedeepya,
Please rebase your repo branch against github master,  address the review comments and resubmit the pull request.

Thanks,
Alex

2020-08-30 22:17 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/model/port/AmqpPort.java
>      long getTotalConnectionCount();
As total is used for gauges in prometheus, this metric can be called overall_connections_count or aggregate_connection_count

2020-08-30 22:17 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/virtualhost/QueueManagingVirtualHost.java
> +            description = "Total number of messaging connections made to this virtualhost since broker startup", metricName = "connections_since_startup_count")
The metric name is inconsistent with the same metric name on amqp port . Possibly, overall_connections_count or aggregate_connection_count could be a better name for the metric.

2020-08-30 22:17 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/virtualhost/QueueManagingVirtualHost.java
> +            description = "Current size of all messages enqueued by this virtualhost.", metricName = "total_queue_depth_bytes_total")
The Virtual Host metric total_queue_depth_bytes_total contains "total"  twice. It should be renamed into queue_depth_bytes_total

2020-08-30 22:17 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/virtualhost/QueueManagingVirtualHost.java
> +                      description = "Current number of messages enqueued by this virtualhost.", metricName = "total_queue_depth_messages_total")
Total is included twice into metric name. It should be queue_depth_messages_total

2020-08-30 22:17 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/virtualhost/QueueManagingVirtualHost.java
> +            description = "Maximum size of message published into the Virtual Host since start-up.", metricName = "high_water_mark_inbound_messages_total")
Total needs to be removed from water mark metric. The name inbound_message_size_high_watermark would work better here

2020-08-30 22:17 UTC, alex-rufous commented on broker-plugins/prometheus-exporter/src/main/java/org/apache/qpid/server/prometheus/PrometheusContentFactory.java
> +                                                              new IncludeDisabledStatisticPredicate(includeDisabled),
The flag for inclusion of disabled metrics can be set via context variable. Potentially,  the factory can check whether context variable like qpid.metrics.includeDisabled is set to true on the root object.

2020-08-30 22:17 UTC, alex-rufous commented on broker-plugins/prometheus-exporter/src/main/java/org/apache/qpid/server/prometheus/QpidCollector.java
> +                suffix = "_" + statistics.getUnits().toString() + "s";
The metric name functionality can be improved to check whether metric name already ends with unit names. When units are there, skip the unit addition to the suffix

2020-09-01 08:46 UTC, Dedeepya-T commented
Hi Alex, Thanks for taking time to review the code. I have addressed all the above comments and ready for review.

2020-09-01 21:27 UTC, closed without merging