QPID-8473:[Broker-J]Added operational logs for sender links
apache/qpid-broker-j pull request #66
Opened 2020-10-12 13:44 UTC by Dedeepya-T

Added operational logs for sender links attaching to queue and exchange. 
This is implemented specifically for clients using AMQP 1.0 protocol only.

2020-10-12 13:49 UTC, alex-rufous requested changes

2020-10-12 13:49 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/logging/messages/Sender_logmessages.properties
> +CLOSE = SND-1002 : Close : {0} : {1}
Please add new line

2020-10-12 13:49 UTC, alex-rufous commented on broker-core/src/main/java/org/apache/qpid/server/model/PublishingLink.java
> +    String TYPE = "link";
Please rename constant TYPE into TYPE_LINK

2020-10-12 16:28 UTC, Dedeepya-T commented on broker-core/src/main/java/org/apache/qpid/server/model/PublishingLink.java
> +    String TYPE = "link";
Done!

2020-10-12 16:28 UTC, Dedeepya-T commented on broker-core/src/main/java/org/apache/qpid/server/logging/messages/Sender_logmessages.properties
> +CLOSE = SND-1002 : Close : {0} : {1}
Done!

2020-10-12 23:07 UTC, alex-rufous requested changes
Dedeepya,
The changes look good. Please merge them into a single commit

2020-10-13 07:15 UTC, Dedeepya-T commented
> Dedeepya,
> The changes look good. Please merge them into a single commit

Done Alex!

2020-10-14 20:31 UTC, closed without merging